### ISSUE TITLE
Sim does not handle non-sequential mote id numbering

### ISSUE THREAD

**Issue by alexbeltran** [UCMAndesLab/CSE160-Project-Skeleton-Code#4]
Sim does not handle non-sequential mote id number. i.e. If the top file is 1, 20, 32, 50, only note 1 will be updated.

**Comment by Nombies** [comment]
Fixed.
https://github.com/Nombies/CSE160-Project-Skeleton-Code/tree/patch-1

**Comment by alexbeltran** [comment]
Thank you Nombies.
I made a pull request for you and accepted it. 👍
